enable: true
games:
  cn:
    enable: true
    genshin:
      auto_checkin: true
      black_list: []
    hokai2:
      auto_checkin: false
      black_list: []
    honkai3rd:
      auto_checkin: false
      black_list: []
    tears_of_themis:
      auto_checkin: false
      black_list: []
    useragent: Mozilla/5.0(Linux;Android 10;V2001A;wv)AppleWebKit/537.36(KHTML, like Gecko)Version/4.0 Chrome/87.0.4280.141 MobileSafari/537.36 VivoBrowser/11.7.14.6
  os:
    cookie: ''
    enable: false
    genshin:
      auto_checkin: false
      black_list: []
mihoyobbs:
  cancel_like_posts: true
  checkin: true
  checkin_multi: true
  checkin_multi_list:
  - 2
  - 5
  enable: true
  like_posts: true
  read_posts: true
  share_post: true
version: 6
